version: '3.8'

services:
  # FastAPI сервис
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=1727131323
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=friend_finder
    depends_on:
      - db
    volumes:
      - ./app:/app  # Для hot-reload в разработке

  # PostgreSQL сервис
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1727131323
      - POSTGRES_DB=friend_finder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PGAdmin (опционально)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: